"""
algebraaudit.py -- extract the finite algebra carried by selected interfaces.

Stage-1 audit for the selected common-factor program.

The blind-selection run can save exact equalizer winners via --save-winners.
Those winners contain the actual local rule tables.  This module loads the
winner bundle and extracts the algebra generated by interface-local
permutations.

For an interface edge u -> v, the target rule at v is a table

    lambda_v(..., x_u, ...) -> x_v'

For every assignment of the non-interface inputs to v, vary only x_u in
[0, q).  This gives a function f_context : [q] -> [q].  If f_context is a
bijection, it is a permutation of the interface alphabet.  The permutations
seen across all interface edges and all internal contexts generate a finite
permutation group.

Interpretation
--------------
  * C_q / Z_q-like, transitive cyclic group: finite phase candidate.
  * V4, D4, S4, etc.: finite label/gauge-like symmetry, but not U(1)-like.
  * trivial or few permutations: selected exact S exists, but the local rule
    tables are not permutive on the raw interface alphabet.

This is an analysis pass on saved winners, not a new topology experiment.
Winner pickle files are local artifacts; do not load them from untrusted
sources.
"""
from __future__ import annotations

import argparse
import itertools
import json
import math
import os
from collections import Counter, deque
from typing import Iterable, Literal

import numpy as np
import pandas as pd

from . import blindselection as BS
from . import scdcdiamond as S

EdgeFamily = Literal["BC", "BD", "CA", "DA", "all"]


# --------------------------------------------------------------------------- #
# Small permutation group utilities
# --------------------------------------------------------------------------- #
def identity_perm(q: int) -> tuple[int, ...]:
    return tuple(range(int(q)))


def compose_perm(p: tuple[int, ...], r: tuple[int, ...]) -> tuple[int, ...]:
    """Composition p ∘ r, i.e. apply r first, then p."""
    return tuple(p[i] for i in r)


def inverse_perm(p: tuple[int, ...]) -> tuple[int, ...]:
    inv = [0] * len(p)
    for i, j in enumerate(p):
        inv[int(j)] = int(i)
    return tuple(inv)


def perm_power(p: tuple[int, ...], n: int) -> tuple[int, ...]:
    out = identity_perm(len(p))
    for _ in range(int(n)):
        out = compose_perm(p, out)
    return out


def perm_order(p: tuple[int, ...]) -> int:
    e = identity_perm(len(p))
    x = e
    for n in range(1, math.factorial(len(p)) + 1):
        x = compose_perm(p, x)
        if x == e:
            return n
    return -1


def perm_parity(p: tuple[int, ...]) -> int:
    inv = 0
    for i in range(len(p)):
        for j in range(i + 1, len(p)):
            if p[i] > p[j]:
                inv += 1
    return inv % 2


def generated_group(generators: Iterable[tuple[int, ...]], q: int) -> set[tuple[int, ...]]:
    """Return the subgroup of S_q generated by the given permutations."""
    q = int(q)
    gens = {tuple(map(int, g)) for g in generators if len(tuple(g)) == q}
    gens = {g for g in gens if sorted(g) == list(range(q))}
    if not gens:
        return {identity_perm(q)}
    gens |= {inverse_perm(g) for g in list(gens)}
    e = identity_perm(q)
    group: set[tuple[int, ...]] = {e}
    queue: deque[tuple[int, ...]] = deque([e])
    while queue:
        h = queue.popleft()
        for g in gens:
            for new in (compose_perm(g, h), compose_perm(h, g)):
                if new not in group:
                    group.add(new)
                    queue.append(new)
                    # Safety: cannot exceed |S_q|.
                    if len(group) > math.factorial(q):
                        raise RuntimeError("permutation closure exceeded S_q")
    return group


def _cyclic_generated_by(p: tuple[int, ...]) -> set[tuple[int, ...]]:
    q = len(p)
    out = {identity_perm(q)}
    x = identity_perm(q)
    for _ in range(1, math.factorial(q) + 1):
        x = compose_perm(p, x)
        out.add(x)
        if x == identity_perm(q):
            break
    return out


def is_abelian(group: set[tuple[int, ...]]) -> bool:
    gl = list(group)
    for a in gl:
        for b in gl:
            if compose_perm(a, b) != compose_perm(b, a):
                return False
    return True


def is_cyclic(group: set[tuple[int, ...]]) -> bool:
    return any(_cyclic_generated_by(g) == group for g in group)


def action_orbits(group: set[tuple[int, ...]], q: int) -> list[list[int]]:
    unseen = set(range(int(q)))
    orbits: list[list[int]] = []
    while unseen:
        s = min(unseen)
        orb = {g[s] for g in group}
        changed = True
        while changed:
            changed = False
            for x in list(orb):
                for g in group:
                    if g[x] not in orb:
                        orb.add(g[x])
                        changed = True
        orbits.append(sorted(orb))
        unseen -= orb
    return orbits


def perm_to_cycles(p: tuple[int, ...]) -> str:
    seen = [False] * len(p)
    cycles = []
    for i in range(len(p)):
        if seen[i]:
            continue
        cur = []
        j = i
        while not seen[j]:
            seen[j] = True
            cur.append(j)
            j = p[j]
        if len(cur) > 1:
            cycles.append("(" + " ".join(map(str, cur)) + ")")
    return "".join(cycles) if cycles else "()"


def classify_group(group: set[tuple[int, ...]], q: int) -> dict:
    q = int(q)
    order = len(group)
    abelian = is_abelian(group)
    cyclic = is_cyclic(group)
    all_even = all(perm_parity(g) == 0 for g in group)
    orbits = action_orbits(group, q)
    transitive = len(orbits) == 1
    elem_orders = Counter(perm_order(g) for g in group)

    name = f"subgroup_order_{order}"
    if order == 1:
        name = "trivial"
    elif cyclic:
        name = f"C{order}"
    # Common noncyclic subgroups of S4/S5; these names are structural hints.
    if q == 4:
        if order == 4 and abelian and not cyclic:
            name = "V4"
        elif order == 6 and not abelian:
            name = "S3"
        elif order == 8 and not abelian:
            name = "D4"
        elif order == 12 and all_even:
            name = "A4"
        elif order == 24:
            name = "S4"
    elif q == 5:
        if order == 5 and cyclic and transitive:
            name = "C5/Z5"
        elif order == 10 and not abelian:
            name = "D5"
        elif order == 20 and not abelian and transitive:
            name = "AGL(1,5)-like"
        elif order == 60 and all_even:
            name = "A5"
        elif order == 120:
            name = "S5"

    zq_like = bool(cyclic and transitive and order == q)
    symmetric = bool(order == math.factorial(q))
    return dict(
        group_order=int(order),
        group_name=name,
        group_abelian=bool(abelian),
        group_cyclic=bool(cyclic),
        group_transitive=bool(transitive),
        group_all_even=bool(all_even),
        group_zq_like=bool(zq_like),
        group_symmetric=bool(symmetric),
        group_orbits=json.dumps(orbits),
        group_element_order_hist=json.dumps({int(k): int(v) for k, v in sorted(elem_orders.items())}),
    )


# --------------------------------------------------------------------------- #
# Local rule restrictions along interface edges
# --------------------------------------------------------------------------- #
def _rule_index(vals: Iterable[int], q: int) -> int:
    idx = 0
    p = 1
    for v in vals:
        idx += int(v) * p
        p *= int(q)
    return int(idx)


def _context_rows(n: int, q: int):
    if n <= 0:
        yield ()
    else:
        yield from itertools.product(range(int(q)), repeat=int(n))


def restricted_functions_for_edge(ds: S.SCDCDiamond, edge: tuple[int, int]) -> list[dict]:
    """All raw functions [q] -> [q] obtained by varying edge source only."""
    src, tgt = map(int, edge)
    preds = tuple(int(x) for x in ds.joint.preds[tgt])
    positions = [i for i, p in enumerate(preds) if p == src]
    if len(positions) != 1:
        # The present diamond has one explicit interface edge; return a marked row
        # rather than silently doing the wrong thing on unusual multigraphs.
        return [dict(edge=(src, tgt), target=tgt, source=src, status=f"source_position_count_{len(positions)}")]
    pos = positions[0]
    other_positions = [i for i in range(len(preds)) if i != pos]
    out: list[dict] = []
    rule = ds.joint.rules[tgt]
    for ctx in _context_rows(len(other_positions), ds.q):
        vals = [0] * len(preds)
        for j, ppos in enumerate(other_positions):
            vals[ppos] = int(ctx[j])
        f = []
        for a in range(ds.q):
            vals[pos] = int(a)
            f.append(int(rule[_rule_index(vals, ds.q)]))
        ft = tuple(f)
        rank = len(set(ft))
        is_perm = sorted(ft) == list(range(ds.q))
        out.append(dict(
            edge=(src, tgt),
            source=src,
            target=tgt,
            status="ok",
            context=tuple(int(x) for x in ctx),
            function=ft,
            rank=int(rank),
            is_permutation=bool(is_perm),
            permutation=ft if is_perm else None,
        ))
    return out


def interface_edges(ds: S.SCDCDiamond, family: EdgeFamily = "all") -> dict[str, tuple[tuple[int, int], ...]]:
    fam = {
        "BC": tuple(ds.interface_BC),
        "BD": tuple(ds.interface_BD),
        "CA": tuple(ds.interface_CA),
        "DA": tuple(ds.interface_DA),
    }
    if family == "all":
        return fam
    return {family: fam[family]}


def audit_edge_family(ds: S.SCDCDiamond, family: EdgeFamily = "all") -> dict:
    fam = interface_edges(ds, family)
    rows = []
    edge_summaries = {}
    all_perms = []
    for name, edges in fam.items():
        edge_perms = []
        edge_total = 0
        edge_perm_contexts = 0
        edge_rank_hist = Counter()
        edge_fn_hist = Counter()
        for edge in edges:
            frows = restricted_functions_for_edge(ds, edge)
            for r in frows:
                if r.get("status") != "ok":
                    continue
                rows.append((name, edge, r))
                edge_total += 1
                edge_rank_hist[int(r["rank"])] += 1
                edge_fn_hist[tuple(r["function"])] += 1
                if r["is_permutation"]:
                    p = tuple(int(x) for x in r["permutation"])
                    edge_perm_contexts += 1
                    edge_perms.append(p)
                    all_perms.append(p)
        g = generated_group(edge_perms, ds.q)
        edge_summaries[name] = dict(
            n_edges=int(len(edges)),
            contexts_total=int(edge_total),
            permutation_contexts=int(edge_perm_contexts),
            permutation_fraction=float(edge_perm_contexts / edge_total) if edge_total else math.nan,
            unique_permutations=int(len(set(edge_perms))),
            rank_hist={int(k): int(v) for k, v in sorted(edge_rank_hist.items())},
            top_functions=[dict(function=list(map(int, k)), count=int(v), is_permutation=(sorted(k) == list(range(ds.q)))) for k, v in edge_fn_hist.most_common(8)],
            generators=[perm_to_cycles(p) for p in sorted(set(edge_perms))],
            **classify_group(g, ds.q),
        )
    group = generated_group(all_perms, ds.q)
    agg = classify_group(group, ds.q)
    agg.update(
        contexts_total=int(sum(v["contexts_total"] for v in edge_summaries.values())),
        permutation_contexts=int(sum(v["permutation_contexts"] for v in edge_summaries.values())),
        permutation_fraction=float(
            sum(v["permutation_contexts"] for v in edge_summaries.values()) /
            max(1, sum(v["contexts_total"] for v in edge_summaries.values()))
        ),
        unique_permutation_generators=int(len(set(all_perms))),
        generator_cycles=json.dumps([perm_to_cycles(p) for p in sorted(set(all_perms))]),
        edge_summaries=json.dumps(edge_summaries),
    )
    return agg


# --------------------------------------------------------------------------- #
# Bundle audit / plotting / CLI
# --------------------------------------------------------------------------- #
def load_winner_bundle(path: str) -> list[dict]:
    return BS.load_winner_records(path)


def run_algebra_audit(
    winner_path: str,
    *,
    top_n: int = 20,
    edge_family: EdgeFamily = "all",
    verbose: bool = True,
) -> pd.DataFrame:
    records = load_winner_bundle(winner_path)
    if top_n > 0:
        records = records[: int(top_n)]
    rows = []
    for i, rec in enumerate(records):
        ds = rec.get("diamond")
        if ds is None:
            raise ValueError(f"winner record {i} has no diamond object")
        metrics = rec.get("metrics", {}) or {}
        row = dict(
            candidate_index=int(i),
            q=int(ds.q),
            w=int(ds.w),
            kB=int(ds.kB),
            kC=int(ds.kC),
            kD=int(ds.kD),
            kA=int(ds.kA),
            saved_run=metrics.get("run", None),
            saved_generation=metrics.get("generation", None),
            saved_candidate=metrics.get("candidate", None),
            saved_exact_residual_qcoords=metrics.get("exact_residual_qcoords", None),
            saved_blind_fitness=metrics.get("blind_fitness", None),
        )
        row.update(audit_edge_family(ds, edge_family))
        rows.append(row)
        if verbose:
            print(
                f"algebra winner={i} group={row['group_name']} order={row['group_order']} "
                f"zq_like={row['group_zq_like']} perm_frac={row['permutation_fraction']:.3f}",
                flush=True,
            )
    return pd.DataFrame(rows)


def analyze_algebra_audit(df: pd.DataFrame) -> dict:
    if df.empty:
        return {"verdict": "NO DATA"}
    name_counts = df["group_name"].value_counts().to_dict()
    zq_frac = float(df["group_zq_like"].mean()) if "group_zq_like" in df else 0.0
    sym_frac = float(df["group_symmetric"].mean()) if "group_symmetric" in df else 0.0
    trans_frac = float(df["group_transitive"].mean()) if "group_transitive" in df else 0.0
    abel_frac = float(df["group_abelian"].mean()) if "group_abelian" in df else 0.0
    mean_order = float(df["group_order"].mean())
    mean_perm_frac = float(df["permutation_fraction"].mean())
    q_vals = sorted(set(int(x) for x in df["q"].dropna().tolist()))

    if zq_frac >= 0.75:
        verdict = "Z_q-LIKE ALGEBRA SIGNAL: selected interfaces generate transitive cyclic phase groups"
    elif sym_frac >= 0.75:
        verdict = "FULL PERMUTATION SIGNAL: selected interfaces generate S_q-like label symmetry, not U(1)-like phase"
    elif trans_frac >= 0.75 and abel_frac < 0.5:
        verdict = "NONABELIAN TRANSITIVE LABEL SYMMETRY: gauge-like, but not electromagnetic U(1)-like"
    elif mean_perm_frac < 0.25:
        verdict = "WEAK LOCAL-PERMUTIVE STRUCTURE: exact S exists but local raw rules rarely act as permutations"
    elif abel_frac >= 0.75:
        verdict = "ABELIAN FINITE LABEL SYMMETRY: possible discrete charge sector; inspect group names"
    else:
        verdict = "MIXED FINITE LABEL ALGEBRAS: inspect edge-level summaries before holonomy design"

    top = df.sort_values(["group_zq_like", "group_order", "permutation_fraction"], ascending=False).head(10)
    return dict(
        verdict=verdict,
        n_winners=int(len(df)),
        q_values=q_vals,
        group_name_counts={str(k): int(v) for k, v in name_counts.items()},
        zq_like_fraction=float(zq_frac),
        symmetric_fraction=float(sym_frac),
        transitive_fraction=float(trans_frac),
        abelian_fraction=float(abel_frac),
        mean_group_order=float(mean_order),
        mean_permutation_fraction=float(mean_perm_frac),
        top_winners=top[[
            "candidate_index", "group_name", "group_order", "group_zq_like",
            "group_abelian", "group_cyclic", "group_transitive",
            "permutation_fraction", "unique_permutation_generators",
            "group_element_order_hist",
        ]].to_dict(orient="records"),
    )


def plot_algebra_audit(df: pd.DataFrame, path: str) -> None:
    import matplotlib
    matplotlib.use("Agg")
    import matplotlib.pyplot as plt

    if df.empty:
        raise ValueError("empty dataframe")
    fig, ax = plt.subplots(1, 3, figsize=(15, 4))
    counts = df["group_name"].value_counts()
    ax[0].bar(range(len(counts)), counts.values)
    ax[0].set_xticks(range(len(counts)))
    ax[0].set_xticklabels(counts.index.tolist(), rotation=30, ha="right")
    ax[0].set_ylabel("winner count")
    ax[0].set_title("generated group type")

    ax[1].scatter(df["permutation_fraction"], df["group_order"], alpha=0.75)
    ax[1].set_xlabel("permutation-context fraction")
    ax[1].set_ylabel("generated group order")
    ax[1].set_title("local permutivity vs algebra size")

    # Element-order histograms as stacked-ish lines by winner.
    for _, row in df.head(12).iterrows():
        hist = json.loads(row["group_element_order_hist"])
        xs = sorted(int(k) for k in hist.keys())
        ys = [hist[str(x)] if str(x) in hist else hist.get(x, 0) for x in xs]
        ax[2].plot(xs, ys, "o-", alpha=0.45)
    ax[2].set_xlabel("element order")
    ax[2].set_ylabel("count in group")
    ax[2].set_title("element-order fingerprints")

    fig.tight_layout()
    os.makedirs(os.path.dirname(path) or ".", exist_ok=True)
    fig.savefig(path, dpi=130)
    plt.close(fig)


def _main(argv: list[str] | None = None) -> int:
    p = argparse.ArgumentParser(description="Extract finite algebra generated by saved blind-selection winners.")
    p.add_argument("winner_path")
    p.add_argument("--top-n", type=int, default=20)
    p.add_argument("--edge-family", choices=["BC", "BD", "CA", "DA", "all"], default="all")
    p.add_argument("--out", default=None)
    p.add_argument("--plot", default=None)
    p.add_argument("--quiet", action="store_true")
    args = p.parse_args(argv)

    df = run_algebra_audit(args.winner_path, top_n=args.top_n, edge_family=args.edge_family, verbose=not args.quiet)
    summary = analyze_algebra_audit(df)
    print(json.dumps(summary, indent=2, default=float))

    if args.out:
        os.makedirs(os.path.dirname(args.out) or ".", exist_ok=True)
        df.to_csv(args.out, index=False)
        root, _ = os.path.splitext(args.out)
        with open(root + "_summary.json", "w", encoding="utf-8") as f:
            json.dump(summary, f, indent=2, default=float)
        if not args.quiet:
            print(f"wrote {args.out}")
            print(f"wrote {root + '_summary.json'}")
    if args.plot:
        plot_algebra_audit(df, args.plot)
        if not args.quiet:
            print(f"wrote {args.plot}")
    return 0


if __name__ == "__main__":
    raise SystemExit(_main())
