"""
blindselection.py -- blind search for rules selected by interface consistency.

Purpose
-------
The rule-selection and approximate-equalizer experiments established two
separate facts:

* maximum-entropy random rule tables usually give a trivial shared interface
  alphabet, |S|=1;
* deliberately structured rules such as copy/permutive/block/canalizing rules
  support nontrivial exact or approximate shared interface labels.

Those structured ensembles are useful controls, but they are not yet a blind
selection test.  This module asks the sharper question:

    If the search objective only knows about interface consistency, does it
    discover nontrivial latent-interface rules?

The search does NOT select for copy accuracy, permutivity, block structure, or
canalization.  Those are reported only afterward as diagnostics.

Implemented search modes
------------------------
``null``
    Independent random-rule samples.  This calibrates the maximum-entropy null.

``evolve``
    A simple population search.  Candidates are random diamonds; descendants are
    generated by random rule-table mutations/resamplings.  Selection keeps the candidates with the largest declared fitness:
    approximate, exact, or a two-stage approximate-then-exact objective.

Fitness modes
-------------
``approx`` uses the approximate equalizer quality from ``approxequalizer.py``.
It is useful as a smooth search heuristic and mutation-robustness diagnostic,
but can be permissive on tiny alphabets.

``exact`` uses the exact interface equalizer residual ``log_q |S|`` from
``interfaceequalizer.py``.  This is the strict zero-error selection target.

``two_stage`` uses ``approx`` for a pretraining phase, then switches to
``exact``.  This lets the search climb a smoother landscape without making the
approximate equalizer the reported discovery criterion.

Interpretation
--------------
A positive blind-selection signal is not merely that a hand-designed copy rule
works.  It is:

    random null low  +  blind search high  +  post-hoc diagnostics show the
    winners have latent-label-preserving structure.

That is the computational form of the rule-selection hypothesis.
"""
from __future__ import annotations

import argparse
import inspect
import json
import math
import os
import pickle
from typing import Iterable, Literal

import numpy as np
import pandas as pd

from . import core as C
from . import approxequalizer as AE
from . import interfaceequalizer as IE
from . import ruleselection as RS
from . import scdcdiamond as S

InitialPool = S.InitialPool
ObserverInit = S.ObserverInit
SearchMode = Literal["null", "evolve"]
TargetMode = Literal["all", "interface", "branch", "sink", "source"]
ProposalMode = Literal["entry", "table", "mixed"]
FitnessMode = Literal["approx", "exact", "two_stage"]
FitnessStage = Literal["approx", "exact"]


# --------------------------------------------------------------------------- #
# Parsing helpers
# --------------------------------------------------------------------------- #
def _parse_ints(text: str) -> tuple[int, ...]:
    return tuple(int(x.strip()) for x in str(text).split(",") if x.strip())


def _parse_floats(text: str) -> tuple[float, ...]:
    return tuple(float(x.strip()) for x in str(text).split(",") if x.strip())


# --------------------------------------------------------------------------- #
# Diamond copying / mutation
# --------------------------------------------------------------------------- #
def clone_diamond(ds: S.SCDCDiamond) -> S.SCDCDiamond:
    """Deep-copy the mutable rule tables of a diamond while keeping topology.

    The SCC skeleton systems ``B``, ``Csys``, ``Dsys``, and ``Askel`` are used
    only for recurrent-pool construction.  Blind search defaults to
    ``initial_pool='all'``; for that physical run the joint system is the object
    that matters.  We still preserve the skeleton references so the dataclass
    remains fully compatible with ``scdcdiamond`` helpers.
    """
    joint = C.RelationalSystem(
        ds.joint.k,
        ds.joint.q,
        [tuple(p) for p in ds.joint.preds],
        [np.asarray(r, dtype=np.int64).copy() for r in ds.joint.rules],
        meta=dict(ds.joint.meta),
    )
    return S.SCDCDiamond(
        B=ds.B,
        Csys=ds.Csys,
        Dsys=ds.Dsys,
        Askel=ds.Askel,
        joint=joint,
        kB=ds.kB,
        kC=ds.kC,
        kD=ds.kD,
        kA=ds.kA,
        q=ds.q,
        w=ds.w,
        offB=ds.offB,
        offC=ds.offC,
        offD=ds.offD,
        offA=ds.offA,
        interface_BC=tuple(ds.interface_BC),
        interface_BD=tuple(ds.interface_BD),
        interface_CA=tuple(ds.interface_CA),
        interface_DA=tuple(ds.interface_DA),
        meta=dict(ds.meta),
    )


def target_vertices(ds: S.SCDCDiamond, target: TargetMode = "interface") -> tuple[int, ...]:
    """Vertices whose rule tables are allowed to mutate.

    ``interface`` is the practical blind-search default: it mutates the rules on
    the declared B -> {C,D} -> A interface pipeline, but does not encode a copy,
    block, or permutation objective.  ``all`` is the stricter full-rule search.
    """
    if target == "all":
        return tuple(range(ds.k_total))
    if target == "source":
        return tuple(ds.offB + j for j in range(ds.w))
    branch: list[int] = []
    branch.extend(t for _s, t in ds.interface_BC)
    branch.extend(t for _s, t in ds.interface_BD)
    if target == "branch":
        return tuple(sorted(set(int(x) for x in branch)))
    sink: list[int] = []
    sink.extend(t for _s, t in ds.interface_CA)
    sink.extend(t for _s, t in ds.interface_DA)
    if target == "sink":
        return tuple(sorted(set(int(x) for x in sink)))
    if target == "interface":
        out: list[int] = []
        out.extend(ds.offB + j for j in range(ds.w))
        out.extend(branch)
        out.extend(sink)
        return tuple(sorted(set(int(x) for x in out)))
    raise ValueError(f"unknown target mode: {target!r}")


def _random_rule(q: int, indeg: int, rng: np.random.Generator) -> np.ndarray:
    return rng.integers(0, int(q), size=int(q) ** int(indeg), dtype=np.int64)


def _mutate_entries(rule: np.ndarray, q: int, rate: float, rng: np.random.Generator) -> tuple[np.ndarray, int]:
    out = np.asarray(rule, dtype=np.int64).copy()
    if out.size == 0 or rate <= 0:
        return out, 0
    mask = rng.random(out.size) < float(rate)
    n = int(mask.sum())
    if n <= 0:
        return out, 0
    jumps = rng.integers(1, int(q), size=n, dtype=np.int64)
    out[mask] = (out[mask] + jumps) % int(q)
    return out, n


def mutate_diamond(
    ds: S.SCDCDiamond,
    rng: np.random.Generator,
    target: TargetMode = "interface",
    proposal_mode: ProposalMode = "mixed",
    entry_rate: float = 0.08,
    table_rate: float = 0.10,
    n_table_mutations: int = 1,
    ensure_change: bool = True,
) -> tuple[S.SCDCDiamond, dict]:
    """Return a mutated clone and a mutation diagnostic dict.

    Selection never sees copy/block/permutation labels.  It only receives the
    approximate equalizer score after the mutation is evaluated.
    """
    child = clone_diamond(ds)
    verts = list(target_vertices(child, target))
    if not verts:
        return child, {"mutation_vertices": "[]", "entry_mutations": 0, "table_mutations": 0}

    entry_changes = 0
    table_changes = 0
    changed_vertices: set[int] = set()

    if proposal_mode not in ("entry", "table", "mixed"):
        raise ValueError(f"unknown proposal mode: {proposal_mode!r}")

    do_table = proposal_mode in ("table", "mixed")
    do_entry = proposal_mode in ("entry", "mixed")

    # Whole-table resampling moves allow escape from local maxima; entry moves
    # give smooth mutation/robustness exploration.
    if do_table and table_rate > 0:
        n_try = max(0, int(n_table_mutations))
        if proposal_mode == "mixed":
            n_try = max(n_try, int(rng.random() < float(table_rate)))
        for _ in range(n_try):
            if proposal_mode == "table" or rng.random() < float(table_rate):
                v = int(rng.choice(verts))
                child.joint.rules[v] = _random_rule(child.q, len(child.joint.preds[v]), rng)
                table_changes += 1
                changed_vertices.add(v)

    if do_entry and entry_rate > 0:
        for v in verts:
            new_rule, n = _mutate_entries(child.joint.rules[v], child.q, entry_rate, rng)
            if n:
                child.joint.rules[v] = new_rule
                entry_changes += int(n)
                changed_vertices.add(int(v))

    if ensure_change and entry_changes == 0 and table_changes == 0:
        v = int(rng.choice(verts))
        r = child.joint.rules[v].copy()
        if r.size:
            idx = int(rng.integers(0, r.size))
            jump = int(rng.integers(1, child.q))
            r[idx] = (int(r[idx]) + jump) % child.q
            child.joint.rules[v] = r
            entry_changes += 1
            changed_vertices.add(v)

    child.meta.update(
        blind_target=str(target),
        blind_proposal_mode=str(proposal_mode),
        entry_rate=float(entry_rate),
        table_rate=float(table_rate),
        mutation_vertices=sorted(int(v) for v in changed_vertices),
    )
    child.joint.meta.update(child.meta)
    return child, {
        "mutation_vertices": json.dumps(sorted(int(v) for v in changed_vertices)),
        "entry_mutations": int(entry_changes),
        "table_mutations": int(table_changes),
    }


# --------------------------------------------------------------------------- #
# Evaluation / scoring
# --------------------------------------------------------------------------- #
def _get_first(row: dict, names: tuple[str, ...], default=0.0):
    """Return the first present, non-null value among several historical names."""
    for name in names:
        if name in row:
            val = row[name]
            try:
                if pd.isna(val):
                    continue
            except Exception:
                pass
            return val
    return default


def _call_approx_equalizer_measure_compat(
    ds: S.SCDCDiamond,
    thresholds: Iterable[float],
    initial_pool: InitialPool,
    observer_init: ObserverInit,
    min_count: int,
    require_mutual: bool,
) -> list[dict]:
    """Call approxequalizer across patch versions.

    Some earlier copies of ``relgauge.approxequalizer`` did not expose
    ``min_count`` or ``require_mutual`` in ``approx_equalizer_measure``.  This
    adapter passes only arguments accepted by the installed version, so the
    blind-search module remains compatible with both local trees.
    """
    kwargs = dict(
        ds=ds,
        eq_mode="joint",
        thresholds=tuple(float(t) for t in thresholds),
        initial_pool=initial_pool,
        observer_init=observer_init,
        min_count=min_count,
        require_mutual=require_mutual,
    )
    try:
        sig = inspect.signature(AE.approx_equalizer_measure)
        allowed = set(sig.parameters)
        filtered = {k: v for k, v in kwargs.items() if k in allowed}
        # ``ds`` may be positional-only in a future refactor; support both.
        if "ds" in filtered:
            return AE.approx_equalizer_measure(**filtered)
        return AE.approx_equalizer_measure(ds, **{k: v for k, v in filtered.items() if k != "ds"})
    except TypeError as exc:
        # Last-resort compatibility path for the original simple signature.
        if "unexpected keyword" not in str(exc):
            raise
        return AE.approx_equalizer_measure(
            ds,
            eq_mode="joint",
            thresholds=tuple(float(t) for t in thresholds),
            initial_pool=initial_pool,
            observer_init=observer_init,
        )


def _normalize_approx_row(row: dict, width: int) -> dict:
    """Add canonical names expected by blind selection.

    The approximate-equalizer module went through two naming schemes.  Older
    rows used names such as ``approx_info_qcoords`` and
    ``same_component_mass``; newer rows use names such as
    ``approx_quality_score`` and ``approx_inlier_mass_fraction``.  Normalize so
    selection is based on the same scalar either way.
    """
    out = dict(row)
    residual = float(_get_first(out, (
        "approx_residual_qcoords",
        "aeq_approx_residual_qcoords",
        "residual_qcoords",
    ), 0.0))
    inlier = float(_get_first(out, (
        "approx_inlier_mass_fraction",
        "same_component_mass",
        "aeq_approx_same_component_mass",
        "inlier_mass_fraction",
    ), 1.0))
    cross = float(_get_first(out, (
        "approx_cross_mass_fraction",
        "cross_component_mass",
        "aeq_approx_cross_component_mass",
    ), max(0.0, 1.0 - inlier)))
    balance = float(_get_first(out, (
        "approx_component_balance",
        "component_balance",
        "aeq_component_balance",
    ), 1.0 if residual > 0 else 0.0))
    info = float(_get_first(out, (
        "approx_info_qcoords",
        "aeq_approx_info_qcoords",
        "approx_label_mi_norm",
        "approx_raw_panel_mi_norm",
    ), 0.0))

    # Prefer the module's quality score when present.  Otherwise reconstruct a
    # conservative consistency-only score from residual, inlier mass, and
    # component balance.  The optional info term is only used to break ties; it
    # does not create selected candidates without nontrivial residual.
    quality = _get_first(out, ("approx_quality_score", "quality_score", "aeq_quality_score"), None)
    if quality is None:
        quality = (residual / max(1, int(width))) * max(0.0, inlier) * max(0.0, balance)
        quality += 1e-6 * max(0.0, info)
    quality = float(quality)

    out.update(
        approx_residual_qcoords=float(residual),
        approx_inlier_mass_fraction=float(inlier),
        approx_cross_mass_fraction=float(cross),
        approx_component_balance=float(balance),
        approx_info_qcoords=float(info),
        approx_quality_score=float(quality),
    )
    return out



def _exact_equalizer_metrics(
    ds: S.SCDCDiamond,
    initial_pool: InitialPool = "all",
    observer_init: ObserverInit = "zero",
) -> dict:
    """Strict zero-error interface equalizer metrics for one candidate.

    This is the exact shared alphabet ``S`` used as the primary discovery
    criterion in ``fitness_mode='exact'`` and the second stage of
    ``fitness_mode='two_stage'``.  No product-local quotient is computed here;
    this is the relational interface equalizer only.
    """
    row = IE.interface_equalizer_measure(
        ds,
        eq_mode="joint",
        initial_pool=initial_pool,
        observer_init=observer_init,
        compare_product=False,
    )
    residual = float(row.get("eq_residual_qcoords", 0.0))
    cost = float(row.get("eq_cost_qcoords", math.nan))
    shared = float(row.get("eq_shared_classes_mean", row.get("eq_shared_classes", 0.0)))
    edge = float(row.get("eq_edge_density_mean", row.get("eq_edge_density", math.nan)))
    out = {
        "exact_residual_qcoords": residual,
        "exact_cost_qcoords": cost,
        "exact_residual_per_width": float(residual / ds.w) if ds.w else math.nan,
        "exact_shared_classes_mean": shared,
        "exact_edge_density_mean": edge,
        "exact_selected": bool(residual > 1e-12),
    }
    # Keep the raw exact fields with a prefix so audit scripts can recover the
    # equalizer details without recomputing them.
    for k, v in row.items():
        if k.startswith("eq_"):
            out[f"exact_{k}"] = v
    return out


def _score_candidate(
    out: dict,
    fitness_stage: FitnessStage = "approx",
    selection_threshold_qcoords: float = 1e-9,
    quality_threshold: float = 0.10,
    exact_tie_breaker: float = 1e-6,
) -> dict:
    """Attach blind fitness / selection fields for a chosen stage."""
    approx_quality = float(out.get("approx_quality_score", 0.0))
    approx_residual = float(out.get("approx_residual_qcoords", 0.0))
    exact_residual = float(out.get("exact_residual_qcoords", 0.0))
    exact_cost = float(out.get("exact_cost_qcoords", math.nan))

    if fitness_stage == "approx":
        fitness = approx_quality
        residual = approx_residual
        selected = bool((residual > float(selection_threshold_qcoords)) and (fitness >= float(quality_threshold)))
    elif fitness_stage == "exact":
        # Exact |S| is the discovery criterion.  The approximate quality is used
        # only as an infinitesimal deterministic tie-breaker among candidates
        # with the same exact residual.
        fitness = exact_residual + float(exact_tie_breaker) * approx_quality
        residual = exact_residual
        selected = bool(exact_residual > float(selection_threshold_qcoords))
    else:
        raise ValueError(f"unknown fitness stage: {fitness_stage!r}")

    out.update(
        blind_fitness=float(fitness),
        blind_residual_qcoords=float(residual),
        blind_fitness_stage=str(fitness_stage),
        blind_primary_metric=("approx_quality_score" if fitness_stage == "approx" else "exact_residual_qcoords"),
        selected_blind=bool(selected),
        selection_threshold_qcoords=float(selection_threshold_qcoords),
        quality_threshold=float(quality_threshold),
        exact_tie_breaker=float(exact_tie_breaker),
    )
    # Convenience aliases used by plotting/analysis in both old and new runs.
    out.setdefault("approx_residual_qcoords", float(approx_residual))
    out.setdefault("exact_residual_qcoords", float(exact_residual))
    out.setdefault("exact_cost_qcoords", float(exact_cost))
    return out



def evaluate_candidate(
    ds: S.SCDCDiamond,
    thresholds: Iterable[float] = (0.45, 0.55, 0.65),
    initial_pool: InitialPool = "all",
    observer_init: ObserverInit = "zero",
    min_count: int = 1,
    require_mutual: bool = True,
    selection_threshold_qcoords: float = 1e-9,
    quality_threshold: float = 0.10,
    fitness_stage: FitnessStage = "approx",
    exact_tie_breaker: float = 1e-6,
) -> dict:
    """Evaluate one candidate under an approximate or exact selection stage.

    The function always computes both the approximate equalizer and the exact
    equalizer, so the CSV can audit approximate robustness even when the search
    is selected by exact ``log_q |S|``.
    """
    rows = _call_approx_equalizer_measure_compat(
        ds=ds,
        thresholds=thresholds,
        initial_pool=initial_pool,
        observer_init=observer_init,
        min_count=min_count,
        require_mutual=require_mutual,
    )
    if not rows:
        raise RuntimeError("approx_equalizer_measure returned no rows")
    norm_rows = [_normalize_approx_row(dict(r), width=int(ds.w)) for r in rows]
    best = max(
        norm_rows,
        key=lambda r: (
            float(r.get("approx_quality_score", -math.inf)),
            float(r.get("approx_residual_qcoords", -math.inf)),
            -float(r.get("approx_cross_mass_fraction", math.inf)),
        ),
    )
    out = dict(best)
    out.update(_exact_equalizer_metrics(ds, initial_pool=initial_pool, observer_init=observer_init))
    metrics = RS.interface_rule_diagnostics(ds)
    out.update(metrics)
    return _score_candidate(
        out,
        fitness_stage=fitness_stage,
        selection_threshold_qcoords=selection_threshold_qcoords,
        quality_threshold=quality_threshold,
        exact_tie_breaker=exact_tie_breaker,
    )


def make_random_candidate(
    kB: int,
    kM: int,
    kA: int,
    q: int,
    w: int,
    rng: np.random.Generator,
    extra_B: int | None = None,
    extra_M: int | None = None,
    extra_A: int | None = None,
) -> S.SCDCDiamond:
    ds = S.make_scdc_diamond(
        kB=kB,
        kC=kM,
        kD=kM,
        kA=kA,
        q=q,
        w=w,
        rng=rng,
        extra_B=extra_B,
        extra_C=extra_M,
        extra_D=extra_M,
        extra_A=extra_A,
    )
    ds.meta.update(rule_origin="blind_random")
    ds.joint.meta.update(ds.meta)
    return ds



# --------------------------------------------------------------------------- #
# Winner serialization
# --------------------------------------------------------------------------- #
def _to_builtin(v):
    """Convert common numpy/pandas scalar values to pickle/JSON-friendly values."""
    if isinstance(v, (np.integer,)):
        return int(v)
    if isinstance(v, (np.floating,)):
        return float(v)
    if isinstance(v, (np.bool_,)):
        return bool(v)
    try:
        if pd.isna(v):
            return None
    except Exception:
        pass
    return v


def _metrics_snapshot(metrics: dict) -> dict:
    return {str(k): _to_builtin(v) for k, v in dict(metrics).items()}


def make_winner_record(ds: S.SCDCDiamond, metrics: dict) -> dict:
    """Return a self-contained pickle record for a selected candidate.

    The record stores a cloned ``SCDCDiamond`` object, not just CSV metrics, so
    later audit tools can recompute exact equalizers, source dependence,
    persistence, and mutation robustness.  The pickle is intended for local
    experiment artifacts only; do not load winner files from untrusted sources.
    """
    return {
        "format": "relgauge.blindwinner.v1",
        "diamond": clone_diamond(ds),
        "metrics": _metrics_snapshot(metrics),
    }


def _winner_key(record: dict) -> tuple[float, float, float, int]:
    m = record.get("metrics", {})
    return (
        float(m.get("exact_residual_qcoords") or 0.0),
        float(m.get("blind_fitness") or 0.0),
        float(m.get("approx_quality_score") or 0.0),
        int(m.get("generation") or 0),
    )


def _maybe_store_winner(
    store: list[dict] | None,
    ds: S.SCDCDiamond,
    metrics: dict,
    *,
    top_n: int = 20,
    min_exact_residual: float = 1e-9,
    include_null: bool = False,
) -> None:
    """Store candidate snapshots for later common-factor audit.

    By default we keep only evolved candidates whose exact residual is
    nontrivial.  The store is pruned online to the best ``top_n`` records by
    exact residual, blind fitness, approximate quality, and generation.
    """
    if store is None or int(top_n) <= 0:
        return
    if str(metrics.get("search_mode", "")) == "null" and not include_null:
        return
    exact = float(metrics.get("exact_residual_qcoords") or 0.0)
    if exact + 1e-12 < float(min_exact_residual):
        return
    store.append(make_winner_record(ds, metrics))
    # Keep a small buffer of near-best records so later generations can replace
    # earlier duplicates without retaining huge populations.
    max_keep = max(int(top_n), 1)
    if len(store) > 4 * max_keep:
        store.sort(key=_winner_key, reverse=True)
        del store[max_keep:]


def save_winner_records(path: str, records: list[dict], summary: dict | None = None) -> None:
    """Write winner records to a pickle file for ``commonfactoraudit``.

    Pickle is used deliberately because the rule tables and dataclass graph
    objects are numpy-heavy.  Treat these as local artifacts, not interchange
    files from untrusted sources.
    """
    os.makedirs(os.path.dirname(path) or ".", exist_ok=True)
    records = sorted(list(records), key=_winner_key, reverse=True)
    payload = {
        "format": "relgauge.blindwinner.bundle.v1",
        "n_records": int(len(records)),
        "summary": dict(summary or {}),
        "records": records,
    }
    with open(path, "wb") as f:
        pickle.dump(payload, f, protocol=pickle.HIGHEST_PROTOCOL)


def load_winner_records(path: str) -> list[dict]:
    """Load records written by ``save_winner_records``."""
    with open(path, "rb") as f:
        payload = pickle.load(f)
    if isinstance(payload, dict) and "records" in payload:
        return list(payload["records"])
    if isinstance(payload, list):
        return payload
    raise ValueError(f"unrecognized winner bundle format in {path!r}")


# --------------------------------------------------------------------------- #
# Sweeps
# --------------------------------------------------------------------------- #
def run_null_sample(
    kB: int = 2,
    kM: int = 2,
    kA: int = 2,
    w: int = 1,
    q: int = 3,
    n_samples: int = 80,
    thresholds: Iterable[float] = (0.45, 0.55, 0.65),
    initial_pool: InitialPool = "all",
    observer_init: ObserverInit = "zero",
    min_count: int = 1,
    require_mutual: bool = True,
    selection_threshold_qcoords: float = 1e-9,
    quality_threshold: float = 0.10,
    fitness_mode: FitnessMode = "approx",
    exact_tie_breaker: float = 1e-6,
    extra_B: int | None = None,
    extra_M: int | None = None,
    extra_A: int | None = None,
    base_seed: int = 0,
) -> pd.DataFrame:
    rows: list[dict] = []
    for i in range(int(n_samples)):
        seed = (int(base_seed) * 1000003 + int(i) * 9176 + q * 17 + kA * 131 + w * 19) % 2**32
        rng = np.random.default_rng(seed)
        ds = make_random_candidate(kB, kM, kA, q, w, rng, extra_B=extra_B, extra_M=extra_M, extra_A=extra_A)
        m = evaluate_candidate(
            ds,
            thresholds=thresholds,
            initial_pool=initial_pool,
            observer_init=observer_init,
            min_count=min_count,
            require_mutual=require_mutual,
            selection_threshold_qcoords=selection_threshold_qcoords,
            quality_threshold=quality_threshold,
            fitness_stage="exact" if fitness_mode in ("exact", "two_stage") else "approx",
            exact_tie_breaker=exact_tie_breaker,
        )
        m.update(
            search_mode="null",
            run=-1,
            generation=0,
            candidate=i,
            seed=int(seed),
            parent_candidate=-1,
            mutation_vertices="[]",
            entry_mutations=0,
            table_mutations=0,
            target_mode="none",
            proposal_mode="none",
            fitness_mode=str(fitness_mode),
            pretrain_generations=0,
        )
        rows.append(m)
    return pd.DataFrame(rows)


def run_evolution(
    kB: int = 2,
    kM: int = 2,
    kA: int = 2,
    w: int = 1,
    q: int = 3,
    n_runs: int = 5,
    population: int = 16,
    generations: int = 20,
    elite_fraction: float = 0.25,
    immigrant_fraction: float = 0.10,
    target: TargetMode = "interface",
    proposal_mode: ProposalMode = "mixed",
    entry_rate: float = 0.08,
    table_rate: float = 0.10,
    n_table_mutations: int = 1,
    thresholds: Iterable[float] = (0.45, 0.55, 0.65),
    initial_pool: InitialPool = "all",
    observer_init: ObserverInit = "zero",
    min_count: int = 1,
    require_mutual: bool = True,
    selection_threshold_qcoords: float = 1e-9,
    quality_threshold: float = 0.10,
    fitness_mode: FitnessMode = "approx",
    pretrain_generations: int | None = None,
    exact_tie_breaker: float = 1e-6,
    extra_B: int | None = None,
    extra_M: int | None = None,
    extra_A: int | None = None,
    base_seed: int = 0,
    verbose: bool = True,
    winner_store: list[dict] | None = None,
    winner_top_n: int = 20,
    winner_min_exact_residual: float = 1e-9,
) -> pd.DataFrame:
    rows: list[dict] = []
    population = max(2, int(population))
    n_runs = max(1, int(n_runs))
    generations = max(0, int(generations))
    n_elite = max(1, int(math.ceil(population * float(elite_fraction))))
    n_imm = max(0, int(round(population * float(immigrant_fraction))))
    if fitness_mode not in ("approx", "exact", "two_stage"):
        raise ValueError(f"unknown fitness_mode: {fitness_mode!r}")
    if pretrain_generations is None or int(pretrain_generations) < 0:
        pretrain_generations = generations // 2
    pretrain_generations = max(0, min(int(pretrain_generations), int(generations)))

    for run in range(n_runs):
        rng = np.random.default_rng((int(base_seed) * 99173 + run * 1009 + q * 37 + kA * 101 + w) % 2**32)
        pop: list[S.SCDCDiamond] = [
            make_random_candidate(kB, kM, kA, q, w, rng, extra_B=extra_B, extra_M=extra_M, extra_A=extra_A)
            for _ in range(population)
        ]
        evals: list[tuple[float, S.SCDCDiamond, dict]] = []
        candidate_counter = 0
        for gen in range(generations + 1):
            evals = []
            for ci, ds in enumerate(pop):
                m = evaluate_candidate(
                    ds,
                    thresholds=thresholds,
                    initial_pool=initial_pool,
                    observer_init=observer_init,
                    min_count=min_count,
                    require_mutual=require_mutual,
                    selection_threshold_qcoords=selection_threshold_qcoords,
                    quality_threshold=quality_threshold,
                    fitness_stage=("approx" if fitness_mode == "approx" or (fitness_mode == "two_stage" and gen < pretrain_generations) else "exact"),
                    exact_tie_breaker=exact_tie_breaker,
                )
                m.update(
                    search_mode="evolve",
                    run=int(run),
                    generation=int(gen),
                    candidate=int(candidate_counter),
                    seed=int(base_seed),
                    parent_candidate=int(ds.meta.get("parent_candidate", -1)),
                    mutation_vertices=json.dumps(ds.meta.get("mutation_vertices", [])),
                    entry_mutations=int(ds.meta.get("entry_mutations", 0)),
                    table_mutations=int(ds.meta.get("table_mutations", 0)),
                    target_mode=str(target),
                    proposal_mode=str(proposal_mode),
                    fitness_mode=str(fitness_mode),
                    pretrain_generations=int(pretrain_generations),
                )
                candidate_counter += 1
                _maybe_store_winner(
                    winner_store,
                    ds,
                    m,
                    top_n=winner_top_n,
                    min_exact_residual=winner_min_exact_residual,
                    include_null=False,
                )
                rows.append(m)
                evals.append((float(m["blind_fitness"]), ds, m))
            evals.sort(key=lambda x: x[0], reverse=True)
            if verbose:
                best = evals[0][2]
                print(
                    f"blind-evolve run={run} gen={gen} stage={best.get('blind_fitness_stage','?')} "
                    f"best_fitness={best['blind_fitness']:.4f} "
                    f"exact={best.get('exact_residual_qcoords', math.nan):.4f} "
                    f"approx={best.get('approx_residual_qcoords', math.nan):.4f} selected={best['selected_blind']}",
                    flush=True,
                )
            if gen >= generations:
                break

            elites = [clone_diamond(ds) for _fit, ds, _m in evals[:n_elite]]
            next_pop: list[S.SCDCDiamond] = []
            # Preserve exact elite candidates.
            next_pop.extend(clone_diamond(e) for e in elites)
            # Add random immigrants.
            for _ in range(min(n_imm, population - len(next_pop))):
                next_pop.append(make_random_candidate(kB, kM, kA, q, w, rng, extra_B=extra_B, extra_M=extra_M, extra_A=extra_A))
            # Fill the rest with mutated elite descendants.
            while len(next_pop) < population:
                parent_idx = int(rng.integers(0, len(elites)))
                parent = elites[parent_idx]
                child, info = mutate_diamond(
                    parent,
                    rng,
                    target=target,
                    proposal_mode=proposal_mode,
                    entry_rate=entry_rate,
                    table_rate=table_rate,
                    n_table_mutations=n_table_mutations,
                    ensure_change=True,
                )
                child.meta.update(
                    parent_candidate=int(evals[parent_idx][2].get("candidate", -1)),
                    entry_mutations=int(info["entry_mutations"]),
                    table_mutations=int(info["table_mutations"]),
                    mutation_vertices=json.loads(info["mutation_vertices"]),
                )
                child.joint.meta.update(child.meta)
                next_pop.append(child)
            pop = next_pop[:population]
    return pd.DataFrame(rows)


def run_blind_selection(
    ks_B: Iterable[int] = (2,),
    ks_M: Iterable[int] = (2,),
    ks_A: Iterable[int] = (2,),
    ws: Iterable[int] = (1,),
    q: int = 3,
    null_samples: int = 80,
    n_runs: int = 5,
    population: int = 16,
    generations: int = 20,
    elite_fraction: float = 0.25,
    immigrant_fraction: float = 0.10,
    target: TargetMode = "interface",
    proposal_mode: ProposalMode = "mixed",
    entry_rate: float = 0.08,
    table_rate: float = 0.10,
    n_table_mutations: int = 1,
    thresholds: Iterable[float] = (0.45, 0.55, 0.65),
    initial_pool: InitialPool = "all",
    observer_init: ObserverInit = "zero",
    min_count: int = 1,
    require_mutual: bool = True,
    selection_threshold_qcoords: float = 1e-9,
    quality_threshold: float = 0.10,
    fitness_mode: FitnessMode = "approx",
    pretrain_generations: int | None = None,
    exact_tie_breaker: float = 1e-6,
    extra_B: int | None = None,
    extra_M: int | None = None,
    extra_A: int | None = None,
    base_seed: int = 0,
    max_joint_states: int = 4 ** 9,
    verbose: bool = True,
    winner_store: list[dict] | None = None,
    winner_top_n: int = 20,
    winner_min_exact_residual: float = 1e-9,
) -> pd.DataFrame:
    rows: list[pd.DataFrame] = []
    for kB in ks_B:
        for kM in ks_M:
            for kA in ks_A:
                if q ** (int(kB) + 2 * int(kM) + int(kA)) > int(max_joint_states):
                    if verbose:
                        print(f"skip kB={kB}, kM={kM}, kA={kA}: joint state space too large", flush=True)
                    continue
                for w in ws:
                    if int(w) > min(int(kB), int(kM)) or int(kA) < 2 * int(w):
                        continue
                    if int(null_samples) > 0:
                        nd = run_null_sample(
                            kB=int(kB), kM=int(kM), kA=int(kA), w=int(w), q=int(q),
                            n_samples=int(null_samples), thresholds=thresholds,
                            initial_pool=initial_pool, observer_init=observer_init,
                            min_count=min_count, require_mutual=require_mutual,
                            selection_threshold_qcoords=selection_threshold_qcoords,
                            quality_threshold=quality_threshold,
                            fitness_mode=fitness_mode, exact_tie_breaker=exact_tie_breaker,
                            extra_B=extra_B, extra_M=extra_M, extra_A=extra_A,
                            base_seed=base_seed + int(kA) * 31 + int(w),
                        )
                        rows.append(nd)
                        if verbose:
                            print(f"blind-null kB={kB}, kM={kM}, kA={kA}, w={w} done", flush=True)
                    if int(n_runs) > 0 and int(population) > 0:
                        ed = run_evolution(
                            kB=int(kB), kM=int(kM), kA=int(kA), w=int(w), q=int(q),
                            n_runs=int(n_runs), population=int(population), generations=int(generations),
                            elite_fraction=elite_fraction, immigrant_fraction=immigrant_fraction,
                            target=target, proposal_mode=proposal_mode,
                            entry_rate=entry_rate, table_rate=table_rate, n_table_mutations=n_table_mutations,
                            thresholds=thresholds, initial_pool=initial_pool, observer_init=observer_init,
                            min_count=min_count, require_mutual=require_mutual,
                            selection_threshold_qcoords=selection_threshold_qcoords,
                            quality_threshold=quality_threshold,
                            fitness_mode=fitness_mode, pretrain_generations=pretrain_generations,
                            exact_tie_breaker=exact_tie_breaker,
                            extra_B=extra_B, extra_M=extra_M, extra_A=extra_A,
                            base_seed=base_seed + int(kA) * 157 + int(w) * 11,
                            verbose=verbose,
                            winner_store=winner_store,
                            winner_top_n=winner_top_n,
                            winner_min_exact_residual=winner_min_exact_residual,
                        )
                        rows.append(ed)
                        if verbose:
                            print(f"blind-evolve kB={kB}, kM={kM}, kA={kA}, w={w} done", flush=True)
    if not rows:
        return pd.DataFrame()
    return pd.concat(rows, ignore_index=True)


# --------------------------------------------------------------------------- #
# Analysis / plotting
# --------------------------------------------------------------------------- #
def _best_per_generation(df: pd.DataFrame) -> pd.DataFrame:
    if df.empty or "generation" not in df.columns:
        return pd.DataFrame()
    evo = df[df["search_mode"] == "evolve"].copy()
    if evo.empty:
        return evo
    idx = evo.groupby(["kB", "kM", "kA", "w", "run", "generation"], dropna=False)["blind_fitness"].idxmax()
    return evo.loc[idx].copy()


def analyze_blind_selection(df: pd.DataFrame, top_n: int = 10) -> dict:
    if df.empty:
        return {"verdict": "NO DATA"}
    eps = 1e-9
    # New runs have both exact and approximate metrics; old runs may only have
    # approximate.  Audit whichever columns are present.
    residual_col = "blind_residual_qcoords" if "blind_residual_qcoords" in df.columns else "approx_residual_qcoords"
    viol = 0
    if "approx_residual_qcoords" in df:
        viol += int((df["approx_residual_qcoords"] < -eps).sum())
        viol += int((df["approx_residual_qcoords"] > df["w"].astype(float) + eps).sum())
    if "exact_residual_qcoords" in df:
        viol += int((df["exact_residual_qcoords"] < -eps).sum())
        viol += int((df["exact_residual_qcoords"] > df["w"].astype(float) + eps).sum())
    if "approx_quality_score" in df:
        viol += int((df["approx_quality_score"] < -eps).sum())
    viol += int((df["blind_fitness"] < -eps).sum())

    null = df[df["search_mode"] == "null"]
    best_gen = _best_per_generation(df)
    final = pd.DataFrame()
    if not best_gen.empty:
        max_gen = best_gen.groupby(["kB", "kM", "kA", "w", "run"], dropna=False)["generation"].transform("max")
        final = best_gen[best_gen["generation"] == max_gen]

    def _safe_mean(s):
        return float(s.mean()) if len(s) else math.nan

    def _best_val(frame: pd.DataFrame, value_col: str, score_col: str = "blind_fitness"):
        if frame.empty or value_col not in frame.columns:
            return math.nan
        idx = frame[score_col].idxmax()
        return float(frame.loc[idx, value_col])

    null_sel = _safe_mean(null["selected_blind"]) if len(null) else math.nan
    null_best = float(null["blind_fitness"].max()) if len(null) else math.nan
    null_best_res = _best_val(null, residual_col)
    null_best_exact = _best_val(null, "exact_residual_qcoords")
    null_best_approx = _best_val(null, "approx_residual_qcoords")

    final_sel = _safe_mean(final["selected_blind"]) if len(final) else math.nan
    final_best = float(final["blind_fitness"].max()) if len(final) else math.nan
    final_best_res = _best_val(final, residual_col)
    final_best_exact = _best_val(final, "exact_residual_qcoords")
    final_best_approx = _best_val(final, "approx_residual_qcoords")

    all_best = float(df["blind_fitness"].max())
    all_best_res = _best_val(df, residual_col)
    all_best_exact = _best_val(df, "exact_residual_qcoords")
    all_best_approx = _best_val(df, "approx_residual_qcoords")

    selected = df[df["selected_blind"]]
    unselected = df[~df["selected_blind"]]
    selected_mi = _safe_mean(selected["rule_interface_mi_norm_mean"]) if "rule_interface_mi_norm_mean" in selected else math.nan
    unselected_mi = _safe_mean(unselected["rule_interface_mi_norm_mean"]) if "rule_interface_mi_norm_mean" in unselected else math.nan
    selected_acc = _safe_mean(selected["rule_interface_copy_accuracy_mean"]) if "rule_interface_copy_accuracy_mean" in selected else math.nan
    unselected_acc = _safe_mean(unselected["rule_interface_copy_accuracy_mean"]) if "rule_interface_copy_accuracy_mean" in unselected else math.nan

    progression = []
    if not best_gen.empty:
        agg = dict(
            best_fitness=("blind_fitness", "max"),
            mean_best_fitness=("blind_fitness", "mean"),
            selected_fraction=("selected_blind", "mean"),
            best_residual=(residual_col, "max"),
            mean_interface_mi=("rule_interface_mi_norm_mean", "mean"),
        )
        if "exact_residual_qcoords" in best_gen.columns:
            agg["best_exact_residual"] = ("exact_residual_qcoords", "max")
        if "approx_residual_qcoords" in best_gen.columns:
            agg["best_approx_residual"] = ("approx_residual_qcoords", "max")
        if "blind_fitness_stage" in best_gen.columns:
            # store the modal stage in a small post-processing step below
            pass
        g = best_gen.groupby("generation").agg(**agg)
        for gen, r in g.iterrows():
            item = dict(
                generation=int(gen),
                best_fitness=float(r.best_fitness),
                mean_best_fitness=float(r.mean_best_fitness),
                selected_fraction=float(r.selected_fraction),
                best_residual=float(r.best_residual),
                mean_interface_mi=float(r.mean_interface_mi),
            )
            if "best_exact_residual" in g.columns:
                item["best_exact_residual"] = float(r.best_exact_residual)
            if "best_approx_residual" in g.columns:
                item["best_approx_residual"] = float(r.best_approx_residual)
            if "blind_fitness_stage" in best_gen.columns:
                stages = best_gen[best_gen.generation == gen]["blind_fitness_stage"].astype(str)
                item["stage"] = stages.mode().iloc[0] if len(stages) else ""
            progression.append(item)

    top = df.sort_values("blind_fitness", ascending=False).head(int(top_n))
    top_rows = []
    cols = [
        "search_mode", "run", "generation", "candidate", "blind_fitness", "blind_residual_qcoords",
        "blind_fitness_stage", "blind_primary_metric", "selected_blind", "exact_residual_qcoords",
        "exact_shared_classes_mean", "exact_cost_qcoords", "exact_edge_density_mean",
        "approx_residual_qcoords", "approx_quality_score", "approx_inlier_mass_fraction",
        "approx_cross_mass_fraction", "approx_shared_classes", "approx_threshold",
        "rule_interface_mi_norm_mean", "rule_interface_copy_accuracy_mean",
        "rule_interface_cond_entropy_bits_mean", "target_mode", "proposal_mode", "fitness_mode",
    ]
    for _, r in top.iterrows():
        row = {}
        for c in cols:
            if c not in r:
                continue
            v = r[c]
            if isinstance(v, (np.floating, float)):
                row[c] = float(v)
            elif isinstance(v, (np.integer, int)) and c not in ("search_mode", "target_mode", "proposal_mode", "fitness_mode", "blind_fitness_stage", "blind_primary_metric"):
                row[c] = int(v)
            else:
                row[c] = v
        top_rows.append(row)

    improvement = None
    if not math.isnan(null_best) and not math.isnan(final_best):
        improvement = float(final_best - null_best)

    # Exact/two-stage success can occur without selected fraction beating the
    # null fraction by 0.2 if the null is calibrated under approximate fitness.
    exact_gain = None
    if not math.isnan(null_best_exact) and not math.isnan(final_best_exact):
        exact_gain = float(final_best_exact - null_best_exact)

    if viol:
        verdict = "IMPLEMENTATION WARNING: blind-selection bounds violated"
    elif (not math.isnan(final_best_exact) and final_best_exact > 1e-9 and (math.isnan(null_best_exact) or final_best_exact > null_best_exact + 1e-9)):
        verdict = "EXACT BLIND-SELECTION SIGNAL: search finds nontrivial exact interface alphabets above the random null"
    elif not math.isnan(final_sel) and final_sel > max(0.20, (0.0 if math.isnan(null_sel) else null_sel + 0.20)) and (math.isnan(null_best) or final_best > null_best + 0.05):
        verdict = "BLIND-SELECTION SIGNAL: consistency search finds nontrivial latent-interface candidates above the random null"
    elif len(selected) > 0 and (math.isnan(null_sel) or _safe_mean(selected["search_mode"].eq("evolve")) > 0):
        verdict = "RARE / PARTIAL BLIND HITS: inspect winners for fine-tuning versus structure"
    else:
        verdict = "NO BLIND-SELECTION SIGNAL in this search budget"

    fitness_modes = sorted(str(x) for x in df.get("fitness_mode", pd.Series([], dtype=str)).dropna().unique())
    return dict(
        verdict=verdict,
        blind_selection_bound_violations=int(viol),
        n_rows=int(len(df)),
        fitness_modes=fitness_modes,
        null_selection_fraction=None if math.isnan(null_sel) else float(null_sel),
        null_best_fitness=None if math.isnan(null_best) else float(null_best),
        null_best_residual_qcoords=None if math.isnan(null_best_res) else float(null_best_res),
        null_best_exact_residual_qcoords=None if math.isnan(null_best_exact) else float(null_best_exact),
        null_best_approx_residual_qcoords=None if math.isnan(null_best_approx) else float(null_best_approx),
        evolved_final_best_selection_fraction=None if math.isnan(final_sel) else float(final_sel),
        evolved_final_best_fitness=None if math.isnan(final_best) else float(final_best),
        evolved_final_best_residual_qcoords=None if math.isnan(final_best_res) else float(final_best_res),
        evolved_final_best_exact_residual_qcoords=None if math.isnan(final_best_exact) else float(final_best_exact),
        evolved_final_best_approx_residual_qcoords=None if math.isnan(final_best_approx) else float(final_best_approx),
        all_time_best_fitness=float(all_best),
        all_time_best_residual_qcoords=float(all_best_res),
        all_time_best_exact_residual_qcoords=None if math.isnan(all_best_exact) else float(all_best_exact),
        all_time_best_approx_residual_qcoords=None if math.isnan(all_best_approx) else float(all_best_approx),
        evolved_improvement_over_null_best=improvement,
        evolved_exact_residual_improvement_over_null=exact_gain,
        mean_selected_interface_mi_norm=None if math.isnan(selected_mi) else float(selected_mi),
        mean_unselected_interface_mi_norm=None if math.isnan(unselected_mi) else float(unselected_mi),
        mean_selected_copy_accuracy=None if math.isnan(selected_acc) else float(selected_acc),
        mean_unselected_copy_accuracy=None if math.isnan(unselected_acc) else float(unselected_acc),
        best_by_generation=progression,
        top_candidates=top_rows,
    )


def plot_blind_selection(df: pd.DataFrame, path: str) -> None:
    import matplotlib

    matplotlib.use("Agg")
    import matplotlib.pyplot as plt

    if df.empty:
        raise ValueError("empty dataframe")
    best_gen = _best_per_generation(df)
    fig, ax = plt.subplots(1, 3, figsize=(15, 4))

    if not best_gen.empty:
        g = best_gen.groupby("generation")["blind_fitness"].agg(["mean", "max"])
        ax[0].plot(g.index, g["mean"], "o-", label="mean run-best")
        ax[0].plot(g.index, g["max"], "s--", label="global best")
        if "exact_residual_qcoords" in best_gen.columns:
            ge = best_gen.groupby("generation")["exact_residual_qcoords"].max()
            ax[0].plot(ge.index, ge.values, "^-", label="best exact |S|")
    null = df[df.search_mode == "null"]
    if len(null):
        ax[0].axhline(null.blind_fitness.max(), linestyle=":", label="null best")
    ax[0].set_xlabel("generation")
    ax[0].set_ylabel("blind fitness")
    ax[0].set_title("fitness selected by consistency")
    ax[0].legend(fontsize=7)

    if not best_gen.empty:
        gsel = best_gen.groupby("generation")["selected_blind"].mean()
        ax[1].plot(gsel.index, gsel.values, "o-")
    ax[1].set_xlabel("generation")
    ax[1].set_ylabel("selected fraction among run-bests")
    ax[1].set_ylim(-0.05, 1.05)
    ax[1].set_title("blind selection over time")

    ax[2].scatter(df["rule_interface_mi_norm_mean"], df["blind_fitness"], s=14, alpha=0.55)
    ax[2].set_xlabel("post-hoc interface-rule MI / log q")
    ax[2].set_ylabel("blind fitness")
    ax[2].set_title("post-hoc structure of blind winners")

    fig.tight_layout()
    os.makedirs(os.path.dirname(path) or ".", exist_ok=True)
    fig.savefig(path, dpi=130)
    plt.close(fig)


# --------------------------------------------------------------------------- #
# CLI
# --------------------------------------------------------------------------- #
def _main(argv: list[str] | None = None) -> int:
    ap = argparse.ArgumentParser(description=__doc__)
    ap.add_argument("q", type=int, nargs="?", default=3)
    ap.add_argument("--ks-B", default="2")
    ap.add_argument("--ks-M", default="2")
    ap.add_argument("--ks-A", default="2")
    ap.add_argument("--ws", default="1")
    ap.add_argument("--null-samples", type=int, default=80)
    ap.add_argument("--runs", type=int, default=5)
    ap.add_argument("--population", type=int, default=16)
    ap.add_argument("--generations", type=int, default=20)
    ap.add_argument("--elite-fraction", type=float, default=0.25)
    ap.add_argument("--immigrant-fraction", type=float, default=0.10)
    ap.add_argument("--target", choices=("all", "interface", "branch", "sink", "source"), default="interface")
    ap.add_argument("--proposal-mode", choices=("entry", "table", "mixed"), default="mixed")
    ap.add_argument("--entry-rate", type=float, default=0.08)
    ap.add_argument("--table-rate", type=float, default=0.10)
    ap.add_argument("--n-table-mutations", type=int, default=1)
    ap.add_argument("--thresholds", default="0.45,0.55,0.65")
    ap.add_argument("--initial-pool", choices=("all", "rec"), default="all")
    ap.add_argument("--observer-init", choices=("zero", "all"), default="zero")
    ap.add_argument("--min-count", type=int, default=1)
    ap.add_argument("--nonmutual", action="store_true", help="use permissive OR thresholding in approximate equalizer")
    ap.add_argument("--selection-threshold", type=float, default=1e-9)
    ap.add_argument("--quality-threshold", type=float, default=0.10)
    ap.add_argument("--fitness", choices=("approx", "exact", "two_stage"), default="approx",
                    help="selection objective: approximate, exact, or approximate pretraining followed by exact")
    ap.add_argument("--pretrain-generations", type=int, default=-1,
                    help="for --fitness two_stage, number of generations selected by approximate fitness; default is generations//2")
    ap.add_argument("--exact-tie-breaker", type=float, default=1e-6,
                    help="tiny weight for approximate quality when exact residual ties")
    ap.add_argument("--extra-B", type=int, default=None)
    ap.add_argument("--extra-M", type=int, default=None)
    ap.add_argument("--extra-A", type=int, default=None)
    ap.add_argument("--base-seed", type=int, default=0)
    ap.add_argument("--max-joint-states", type=int, default=4 ** 9)
    ap.add_argument("--save-winners", default=None,
                    help="pickle file for selected winner rule tables, e.g. example_results/blind_winners.pkl")
    ap.add_argument("--save-winner-top-n", type=int, default=20,
                    help="maximum selected candidate snapshots to keep")
    ap.add_argument("--save-winner-min-exact", type=float, default=1e-9,
                    help="minimum exact residual log_q|S| required for saving a winner")
    ap.add_argument("--out", default="example_results/blind_selection.csv")
    ap.add_argument("--plot", default=None)
    ap.add_argument("--quiet", action="store_true")
    args = ap.parse_args(argv)

    winner_store: list[dict] = []
    df = run_blind_selection(
        ks_B=_parse_ints(args.ks_B),
        ks_M=_parse_ints(args.ks_M),
        ks_A=_parse_ints(args.ks_A),
        ws=_parse_ints(args.ws),
        q=int(args.q),
        null_samples=int(args.null_samples),
        n_runs=int(args.runs),
        population=int(args.population),
        generations=int(args.generations),
        elite_fraction=float(args.elite_fraction),
        immigrant_fraction=float(args.immigrant_fraction),
        target=args.target,  # type: ignore[arg-type]
        proposal_mode=args.proposal_mode,  # type: ignore[arg-type]
        entry_rate=float(args.entry_rate),
        table_rate=float(args.table_rate),
        n_table_mutations=int(args.n_table_mutations),
        thresholds=_parse_floats(args.thresholds),
        initial_pool=args.initial_pool,  # type: ignore[arg-type]
        observer_init=args.observer_init,  # type: ignore[arg-type]
        min_count=int(args.min_count),
        require_mutual=not bool(args.nonmutual),
        selection_threshold_qcoords=float(args.selection_threshold),
        quality_threshold=float(args.quality_threshold),
        fitness_mode=args.fitness,  # type: ignore[arg-type]
        pretrain_generations=(None if int(args.pretrain_generations) < 0 else int(args.pretrain_generations)),
        exact_tie_breaker=float(args.exact_tie_breaker),
        extra_B=args.extra_B,
        extra_M=args.extra_M,
        extra_A=args.extra_A,
        base_seed=int(args.base_seed),
        max_joint_states=int(args.max_joint_states),
        verbose=not bool(args.quiet),
        winner_store=winner_store if args.save_winners else None,
        winner_top_n=int(args.save_winner_top_n),
        winner_min_exact_residual=float(args.save_winner_min_exact),
    )
    os.makedirs(os.path.dirname(args.out) or ".", exist_ok=True)
    df.to_csv(args.out, index=False)
    res = analyze_blind_selection(df)
    if args.save_winners:
        save_winner_records(args.save_winners, winner_store, summary=res)
        res["saved_winners_path"] = args.save_winners
        res["saved_winners_count"] = int(len(winner_store))
    print(json.dumps(res, indent=2, default=float))
    summary_path = os.path.splitext(args.out)[0] + "_summary.json"
    with open(summary_path, "w", encoding="utf-8") as f:
        json.dump(res, f, indent=2, default=float)
    if args.plot:
        plot_blind_selection(df, args.plot)
        print(f"wrote {args.plot}")
    print(f"wrote {args.out}")
    print(f"wrote {summary_path}")
    return 0


if __name__ == "__main__":
    raise SystemExit(_main())
